## Pre-commit configuration
# Last update: 2025-12-23

# Save this file to '/.pre-commit-config.yaml'

repos:
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.9.6
    hooks:
      - id: prettier
        name: prettier
        entry: prettier --write --print-width 220 --prose-wrap never --semi true --single-quote true --tab-width 2 --trailing-comma es5 --ignore-unknown
        language: node
        files: \.(js|jsx|ts|tsx|mjs|cjs|json|css|scss|html|md|yaml|yml)$
        # exclude: \.(html|jsx?)$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: file-contents-sorter
      - id: fix-byte-order-marker
      - id: forbid-submodules
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: requirements-txt-fixer

  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format
      - id: taplo-lint
        args: ['--no-schema']

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 4.3.0
    hooks:
      - id: sqlfluff-fix
        args: ['--dialect=mysql', '--exclude-rules=ambiguous.column_count, layout.long_lines, references.keywords']

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.3
    hooks:
      - id: ruff
        args: ['--fix', '--exit-non-zero-on-fix', '--ignore=BLE001,D103,E501,F821,S102,S110,SIM105,TRY002']
      - id: ruff-format
        args: ['--line-length=220', '--config', "format.quote-style='single'", '--config', "format.indent-style='space'"]

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
      - id: text-unicode-replacement-char

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        args: ['--py314-plus']

default_language_version:
  python: python3
